#! /bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0.5
bspc config window_gap           5
bspc config top_padding          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Opera desktop='^1' follow=on
bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Brave-browser desktop='^1'  follow=on
bspc rule -a Code desktop='^2' follow=on
bspc rule -a Discord desktop='^9' follow=on
bspc rule -a Nemo desktop='^8' follow=on

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

# RESOLUCION ARANDR
xrandr --output VGA-1 --mode 1360x768_60.00


# WALLPAPER
#feh --bg-fill ~/Wallpaper/s4vitar.png &

# POLYBAR
~/.config/polybar/launch.sh

# CUSTOM
killall conky
conky -c $HOME/.config/bspwm/system-overview &
run variety &
numlockx on &


# PICOM
picom &
bspc config border_width 0

xsetroot -cursor_name left_ptr &
